name: Validate Translations

on:
  pull_request:
    paths:
      - 'src/assets/i18n/*.json'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run validation script
        run: |
          npm install
          node scripts/validate-translations.js